name: GraphicalAuth
main: net.gamedoctor.graphicalauth.GraphicalAuth
version: "1.3.1"
api-version: "1.16"
author: _GameDoctor_
description: "Enter the game by drawing!"
website: vk.com/ep_pkp
softdepend: [ PlaceholderAPI ]

commands:
  graphicalauth:
    description: Main GraphicalAuth Command
    aliases:
      - gauth
    usage: /<command>